### ISSUE TITLE
Inconsistencies introduced when opening file?

### ISSUE THREAD

**Issue by waffle911** [gmariani/cv-minerva#61]
After opening a file in Minerva and saving it, the app that originally generated the file no longer recognizes it, even if no modifications were made. However, if I open the file first in Minerva 3.5.0, save it, then open it in Minerva 4.1.3, then save again, the app that generated the file can read it again. Any file first opened in 4.1.3, or opened a second time in 4.1.3 without first being opened in 3.5.0, becomes unusable by the original app.

As an aside, It's odd how Minerva 3.5.0 seems to multiply the file size by quite a large amount (and the generating app still recognizes the file), but then 4.1.3 takes the bloated file and shrinks it back to its original size.

**Comment by gmariani** [comment]
Minerva 3.5.0 doesn't try to do any compression (atleast how AMF handles
compression) since it's not very well documented. 4.1 does a bit better
with it and has it enabled by default. Which is why sometimes files aren't
read after they are saved. If t's having issues reading in the app after
saving, go to the about window and disable sorting. That way it will read
in the file exactly the same way it was written. That has an effect on how
the file gets compressed and has a better chance of compatibility. Let me
know how that works for you.

**Comment by waffle911** [comment]
Actually, I completely missed that option. It would have made the whole process of finding specific values to edit much less tedious, as sorting was off by default – I was already working with values in the order they had been written.

But this new development is frustrating, maddening – infuriating, even:
Two days ago I could replicate this problem without fail; it occurred every single time. Not so anymore. I no longer have access to the older versions of the files which experienced these problems. Now I can open up any of the currently available versions (generated within the past 24 hours) of the files in 4.1.3 (without first having to use 3.5.0 as an intermediary), make modifications, and save, and the app reads the modified files just fine. The app itself hasn't been updated, only the files it was saving to/loading from. All the currently available versions of the app files can be read after modification in Minerva just fine now whether sorting is enabled or not. I only tried using 4.1.3 again without the workaround today to try your suggestion, and without the older files I can't pinpoint when exactly this change occurred or why.

At this point the only thing I can really do is close the issue since I can no longer replicate it for whatever reason, and I have no way of knowing if the issue might present itself again in the future; at this point it seems unlikely. My apologies for the inconvenience.
